/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_sce_javadna_JavaDNA */

#ifndef _Included_com_sce_javadna_JavaDNA
#define _Included_com_sce_javadna_JavaDNA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    isGoodPointFormat
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sce_javadna_JavaDNA_isGoodPointFormat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getRTValue
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_sce_javadna_JavaDNA_getRTValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getRTTime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sce_javadna_JavaDNA_getRTTime
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getRTTimeUTC
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_getRTTimeUTC
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getRTStatus
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sce_javadna_JavaDNA_getRTStatus
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getRTDesc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sce_javadna_JavaDNA_getRTDesc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getRTUnits
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sce_javadna_JavaDNA_getRTUnits
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistAvg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistAvg
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistAvgUTC
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistAvgUTC
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistSnap
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistSnap
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistSnapUTC
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistSnapUTC
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistMax
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistMax
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistMaxUTC
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistMaxUTC
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistMin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistMin
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    initHistMinUTC
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sce_javadna_JavaDNA_initHistMinUTC
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getNextHist
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sce_javadna_JavaDNA_getNextHist
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getNextHistUTC
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sce_javadna_JavaDNA_getNextHistUTC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    parseDouble
 * Signature: ([B)D
 */
JNIEXPORT jdouble JNICALL Java_com_sce_javadna_JavaDNA_parseDouble
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getServiceEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sce_javadna_JavaDNA_getServiceEntry
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getNextServiceEntry
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sce_javadna_JavaDNA_getNextServiceEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getPointEntry
 * Signature: (Ljava/lang/String;S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sce_javadna_JavaDNA_getPointEntry
  (JNIEnv *, jclass, jstring, jshort);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    getNextPointEntry
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sce_javadna_JavaDNA_getNextPointEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    selectPoint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sce_javadna_JavaDNA_selectPoint__
  (JNIEnv *, jclass);

/*
 * Class:     com_sce_javadna_JavaDNA
 * Method:    selectPoint
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sce_javadna_JavaDNA_selectPoint__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
